import { cn } from "@/lib/utils";
import AppProvider from "@/providers/AppProvider";
import type { Metadata } from "next";
import { Inter, Raleway } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "700"],
  variable: "--font-inter",
});

const raleWay = Raleway({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "700"],
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Optispiders",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.variable, raleWay.className, "antialiased")}>
        <AppProvider>{children}</AppProvider>
        <Toaster />
      </body>
    </html>
  );
}
